export const PROJECTS = [
  {
    title: "Project Nexus",
    categoryKey: "categories.hub",
    descriptionKey: "descriptions.nexus",
    image: "/hub.png",
    lock: true,
    status: "status.released",
  },
  {
    title: "Project Atlas",
    categoryKey: "categories.library",
    descriptionKey: "descriptions.atlas",
    image: "/library.png",
    link: "http://atlas.voidcorp.io",
    lock: false,
    status: "status.released",
  },
  {
    title: "Project NebulaBox",
    categoryKey: "categories.mvp",
    descriptionKey: "descriptions.nebulabox",
    image: "/gift.png",
    lock: false,
    status: "status.build",
    link: "http://beta.nebulabox.fr",
  },
  {
    title: "Project Cipher",
    categoryKey: "categories.futur",
    descriptionKey: "descriptions.cipher",
    image: "/next.png",
    lock: true,
    status: "status.analysis",
  },
  {
    title: "Project Quantum",
    categoryKey: "categories.futur",
    descriptionKey: "descriptions.quantum",
    image: "/next.png",
    lock: true,
    status: "status.idea",
  },
  {
    title: "Project Onyx",
    categoryKey: "categories.futur",
    descriptionKey: "descriptions.onyx",
    image: "/next.png",
    lock: true,
    status: "status.idea",
  },
]
